default: &default
  adapter: postgresql

development:
  <<: *default
  database: onceuponadiy_dev

test:
  <<: *default
  database: onceuponadiy_test

production:
  <<: *default
  database: onceuponadiy_prod
